name: Check Java Code Style
on:
  push:
    paths:
      - '**.java'
    branches: [ master, main ]
  pull_request_target:
    paths:
      - '**.py'

jobs:
  autoyapf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        if: github.event_name == 'push'
        uses: actions/checkout@v3

      - name: Checkout pull request
        if: github.event_name == 'pull_request_target'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      # - uses: axel-op/googlejavaformat-action@v3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     skipCommit: true
      #     args: "--replace"

      - name: Jetbrains style
        uses: findologic/intellij-format-action@v1
        with:
          include-glob: '*.kt,*.java'
          path: .

      - name: Create pull request
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v3
        with:
          author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: "style: format java code (google-style)"
          title: "style: format java code (google-style)"
          body: Reformat to google style.
          branch: code-style

      - name: Commit formatted files
        if: github.event_name == 'pull_request_target'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: EndBug/add-and-commit@v8.0.2
        with:
          default_author: github_actions
          message: "style: format java code (google-style)"
