name: "Check code style"

on:
  push:
    branches: [ main ]
  pull_request_target:


jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check license headers
      uses: apache/skywalking-eyes@v0.3.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          config: .github/licenserc.yml
          mode: fix

    - name: Commit licensed files
      if: github.event_name == 'pull_request_target'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: EndBug/add-and-commit@v8.0.2
      with:
        default_author: github_actions
        message: "chore: add license header(s)"

    - name: Create pull request
      if: github.event_name == 'push'
      uses: peter-evans/create-pull-request@v3
      with:
        author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
        commit-message: "chore: add license header(s)"
        title: "chore: add license header(s)"
        body: Add missing license header(s) in source and test code.
        branch: add-license

    # only check code format for PR, single reformatting jobs don't deserve a PR

    - name: Check pep8 format
      if: github.event_name == 'pull_request_target'
      uses: peter-evans/autopep8@v1
      with:
        args: --recursive --in-place --aggressive --aggressive .

    - name: Commit formatted code
      if: github.event_name == 'pull_request_target'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: EndBug/add-and-commit@v8.0.2
      with:
        default_author: github_actions
        message: "style: format python code (pep8)"
